#
# Docker compose file

version : '3.8'
services:
    time_manager:
        container_name: timemanager_api
        image: brysey/timemanager_api
        build:
            context: ./time_manager
        environment:
            PGUSER: postgres
            PGPASSWORD: "postgres"
            PGDATABASE: api_dev
            PGPORT: 5432
            PGHOST: db
        ports:
            - "4000:4000"
        depends_on:
            - db
    db:
        container_name: time_manager-database-1
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        restart: always
        volumes:
            - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
            - "dbdata:/var/lib/postgresql/data"
volumes:
    dbdata:
