apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-10
  namespace: par10
  labels:
    app: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      restartPolicy: Always
      containers:
      - name: backend-deployment
        image: docker.io/brysey/timemanager_api:1.0.0
        env: 
          - name: PGUSER
            valueFrom: 
              secretKeyRef:
                name: database10-secret
                key: pg_user
          - name: PGPASSWORD
            valueFrom: 
              secretKeyRef:
                name: database10-secret
                key: pg_password
          - name: PGHOST
            valueFrom: 
              configMapKeyRef:
                name: postgres10-config
                key: pg_host
          - name: PGDATABASE
            valueFrom: 
              configMapKeyRef:
                name: postgres10-config
                key: pg_database
          - name: PGPORT
            valueFrom: 
              configMapKeyRef:
                name: postgres10-config
                key: pg_port
        ports:
        - containerPort: 4000
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service-10
  namespace: par10
spec:
  type: LoadBalancer
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000